---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cron-chart-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cron-chart
        image: master_cfc_8500_admin_lcn-cron_latest
    spec:
      hostNetwork: false
      containers:
      - name: cron-chart
        image: master.cfc:8500/admin/lcn-cron:latest
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 80
        resources:
          limits:
            cpu: 0.5m
            memory: 15Mi
      imagePullSecrets:
      - name: admin.registrykey
